USE APPLICATION PACKAGE <% ctx.entities.pkg.identifier %>;

CREATE SCHEMA IF NOT EXISTS SHARED_SCHEMA;
USE SCHEMA SHARED_SCHEMA;

CREATE OR REPLACE SECURE VIEW OSM_DATA AS (
SELECT 
    'ors_spcs_stage' as STAGE,
     RELATIVE_PATH, 
    GET_PRESIGNED_URL(@OPENROUTESERVICE_SETUP.PUBLIC.ORS_SPCS_STAGE, RELATIVE_PATH, 3600) AS DOWNLOAD_URL 
FROM DIRECTORY(@OPENROUTESERVICE_SETUP.PUBLIC.ORS_SPCS_STAGE)
union all 
SELECT 
    'ors_graphs_spcs_stage' as STAGE,
     RELATIVE_PATH, 
    GET_PRESIGNED_URL(@OPENROUTESERVICE_SETUP.PUBLIC.ORS_GRAPHS_SPCS_STAGE, RELATIVE_PATH, 3600) AS DOWNLOAD_URL 
FROM DIRECTORY(@OPENROUTESERVICE_SETUP.PUBLIC.ORS_GRAPHS_SPCS_STAGE)
union all 
SELECT 
    'ors_graphs_spcs_stage' as STAGE,
    RELATIVE_PATH, 
    GET_PRESIGNED_URL(@OPENROUTESERVICE_SETUP.PUBLIC.ORS_ELEVATION_CACHE_SPCS_STAGE, RELATIVE_PATH, 3600) AS DOWNLOAD_URL 
FROM DIRECTORY(@OPENROUTESERVICE_SETUP.PUBLIC.ORS_ELEVATION_CACHE_SPCS_STAGE)
);

ALTER STAGE OPENROUTESERVICE_SETUP.PUBLIC.ORS_SPCS_STAGE REFRESH;
ALTER STAGE OPENROUTESERVICE_SETUP.PUBLIC.ORS_GRAPHS_SPCS_STAGE REFRESH;
ALTER STAGE OPENROUTESERVICE_SETUP.PUBLIC.ORS_ELEVATION_CACHE_SPCS_STAGE REFRESH;

GRANT REFERENCE_USAGE ON DATABASE OPENROUTESERVICE_SETUP TO SHARE IN APPLICATION PACKAGE <% ctx.entities.pkg.identifier %>;	
GRANT USAGE ON SCHEMA SHARED_SCHEMA TO SHARE IN APPLICATION PACKAGE <% ctx.entities.pkg.identifier %>;
GRANT SELECT ON VIEW OSM_DATA TO SHARE IN APPLICATION PACKAGE <% ctx.entities.pkg.identifier %>;